### ISSUE TITLE
geolocation widget which points user's current location-Requirement 

### ISSUE THREAD

**Issue by HideBa** [eukarya-inc/reearth-plateauview#13]
###  **Todo**
we need to create plugin as widget that points to the user's current location according to below requirements : 

-  The widget should offer below Modes  : 

1. Button Mode with auto follow option: 
     - If the auto follow is disabled the camera fly to the mouse click on the map
     - if the auto follow is enabled the camera will look at  wherever the mouse move
2. UI Mode :
    - The  user can press on the button and it will show him a UI that show the current location , then the UI gives the user the 
       ability to either keep flying to the location or keep following the location.

###Memo
The design URL : https://www.figma.com/file/3J7vcPRbtHkY6RYCyw5Jfy/Plugins-UI?node-id=764%3A16418&t=OYeXmFr1FuRhPntg-0

**Comment by lavalse** [comment]
And also support switching the Color Theme. I will update the design file to more details.

**Comment by lavalse** [comment]
Color Theme design file is [here](https://www.figma.com/file/3J7vcPRbtHkY6RYCyw5Jfy/Plugins-UI?node-id=872%3A17666&t=md7DclPtKpy8ix2j-1).
